export type TemplateSeed = {
  week: number; day: string; platform: 'instagram' | 'facebook' | 'tiktok';
  format: string; pillar: string; hook: string; cta: string; notes?: string;
};

export const SKJUL_CALENDAR_ID = 'skjul-organisk-v1';

export const skjulTemplates: TemplateSeed[] = [
  // UKE 1 – «Hvem er vi + problemet»
  {
    week: 1,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Merkevare',
    hook: 'Lanseringsvideo (17 s reklame). «Nytt lokalt: Roverk – bygget for orden.»',
    cta: 'Følg oss',
  },
  {
    week: 1,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Nytte',
    hook: 'Bilde av rotete dunker: «Det første gjestene ser…»',
    cta: 'Lagre',
  },
  {
    week: 1,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Håndverk',
    hook: 'Verksted-klipp: «Slik starter et Roverk Skjul»',
    cta: 'DM «SKJUL»',
  },
  {
    week: 1,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Nytte/FAQ',
    hook: '«Er søppelskur søknadspliktig?» → svar: nei (frittstående)',
    cta: 'Del',
  },
  {
    week: 1,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: '11 s kortversjon: «Skjul dunkene – ferdig montert»',
    cta: 'Få pris',
  },
  {
    week: 1,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Bak kulissene',
    hook: 'Verksted, kaffe, «helg på verkstedet»',
    cta: 'Poll',
  },
  {
    week: 1,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Sitat-kort: «Bygget for orden.» + logo',
    cta: '—',
  },

  // UKE 2 – «Slik funker det + tillit»
  {
    week: 2,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Prosess',
    hook: '«Fra bestilling til ferdig montert – 4 steg»',
    cta: 'DM «SKJUL»',
  },
  {
    week: 2,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Detalj',
    hook: 'Nærbilde spiler + luftespalter: «Luftet, så det ikke lukter»',
    cta: 'Lagre',
  },
  {
    week: 2,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Nytte',
    hook: '«Betal først når det står ferdig» – forklar garantien',
    cta: 'Få pris',
  },
  {
    week: 2,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Produkt',
    hook: 'Størrelser: 2 / 3 / 4 dunker (Standard & XL)',
    cta: 'Kommenter antall',
  },
  {
    week: 2,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Håndverk',
    hook: 'Montering hos (første) kunde / tidsforløp',
    cta: 'DM «SKJUL»',
  },
  {
    week: 2,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'FAQ',
    hook: '«Spør oss om alt» – svar på DM live',
    cta: 'Spørsmål-sticker',
  },
  {
    week: 2,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Grunnleggerens historie: hvorfor Roverk?',
    cta: 'Følg',
  },

  // UKE 3 – «Bevis + variasjon»
  {
    week: 3,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Før/etter',
    hook: 'Første ekte før/etter (eller produktvinkel)',
    cta: 'Lagre + del',
    notes: 'Begynn å bruke ekte før/etter når du har det',
  },
  {
    week: 3,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Nytte',
    hook: '«Passer det din bolig?» ulike bakgrunner (våre 6 bilder)',
    cta: 'DM bilde av dunkene',
  },
  {
    week: 3,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Håndverk',
    hook: 'Detalj: hvordan taket/forankringen løses',
    cta: '—',
  },
  {
    week: 3,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'FAQ',
    hook: '«5 ting folk lurer på» (pris, søknad, tid, dunker, betaling)',
    cta: 'Lagre',
  },
  {
    week: 3,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: '6 s teaser + «Fra 5 490 kr»',
    cta: 'Få pris',
  },
  {
    week: 3,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Bak kulissene',
    hook: 'Leveringsdag / bil lastet med moduler',
    cta: '—',
  },
  {
    week: 3,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: '«Ro og orden»-stemningsbilde',
    cta: 'Følg',
  },

  // UKE 4 – «Skala + community»
  {
    week: 4,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Før/etter',
    hook: 'Ny transformasjon / kundeklipp (m/ samtykke)',
    cta: 'Del',
  },
  {
    week: 4,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Nytte',
    hook: '«Slik måler du opp for riktig størrelse»',
    cta: 'Lagre',
  },
  {
    week: 4,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: '«Standard vs XL – hva passer 370 L-dunker?»',
    cta: 'DM «SKJUL»',
  },
  {
    week: 4,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Merkevare',
    hook: 'Presenter produktfamilien: Skjul · Ved · Orden',
    cta: 'Følg',
  },
  {
    week: 4,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Tilbud',
    hook: 'Introtilbud / ledige monteringsdatoer',
    cta: 'Få pris',
    notes: 'Introtilbud kun hvis ekte',
  },
  {
    week: 4,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Community',
    hook: 'Del en følger-DM/spørsmål (m/ samtykke)',
    cta: 'Spør oss',
  },
  {
    week: 4,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Oppsummering måned 1 + takk',
    cta: 'Følg',
  },
];
