import type { TemplateSeed } from './calendar-skjul';

export const ORDEN_CALENDAR_ID = 'orden-v1';

export const ordenTemplates: TemplateSeed[] = [
  // UKE 1 – «Hvem er vi + problemet»
  {
    week: 1,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Merkevare',
    hook: 'Nytt lokalt: Roverk Orden – slutt på rotet',
    cta: 'Følg',
    notes: 'V01_9x16 (full historie)',
  },
  {
    week: 1,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Nytte',
    hook: 'Rotete garasje eller bod? Alt får sin faste plass',
    cta: 'Lagre',
    notes: 'Bilder hero',
  },
  {
    week: 1,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Håndverk',
    hook: 'Kassene henger i kanten på et rack i ekte tre',
    cta: 'DM «ORDEN»',
    notes: 'V25_9x16 nærbilde',
  },
  {
    week: 1,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Produkt',
    hook: 'Kassene er alltid inkludert – Stor 60 l / Veldig stor 100 l',
    cta: 'Del',
    notes: 'Bilder hero + kasse',
  },
  {
    week: 1,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Nytte/FAQ',
    hook: 'Levert og ferdig montert – ingen flatpakke, ingen helgeprosjekt',
    cta: 'Få pris',
    notes: 'V07_9x16',
  },
  {
    week: 1,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Bak kulissene',
    hook: 'Verksted, kaffe, «helg på verkstedet»',
    cta: 'Poll',
  },
  {
    week: 1,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Design',
    hook: 'Sitat-kort: «Bygget for orden.» + logo',
    cta: '—',
  },

  // UKE 2 – «Slik funker det + pris/verdi»
  {
    week: 2,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Prosess',
    hook: 'Fra bestilling til ferdig montert – betal først når det står ferdig',
    cta: 'DM «ORDEN»',
    notes: 'V07/V08_9x16',
  },
  {
    week: 2,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Tilbud',
    hook: 'Rimeligere enn IKEA-hyller kjøpt og bygget selv (levering + montering inkludert)',
    cta: 'Få pris',
    notes: 'V09/V31 – IKEA-sammenligning holdes ærlig',
  },
  {
    week: 2,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Nytte',
    hook: 'Trill racket dit du vil (hjul som tilvalg)',
    cta: 'Lagre',
    notes: 'V11/V27_9x16 mobilt',
  },
  {
    week: 2,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Produkt',
    hook: 'Størrelser: Liten 1×3 / Mellom 3×4 / Stor 5×5',
    cta: 'Kommenter',
    notes: 'V19–V24 spotlights',
  },
  {
    week: 2,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Håndverk',
    hook: 'Slik henger kassa – nærbilde av håndverket',
    cta: 'DM «ORDEN»',
    notes: 'V25/V26_9x16',
  },
  {
    week: 2,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Bak kulissene',
    hook: 'Spør oss om alt – svar på DM live',
    cta: 'Spørsmål-sticker',
  },
  {
    week: 2,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Grunnleggerens historie: hvorfor Roverk?',
    cta: 'Følg',
  },

  // UKE 3 – «Bevis + FAQ + variasjon»
  {
    week: 3,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Før/etter',
    hook: 'Fra rot til orden',
    cta: 'Lagre + del',
    notes: 'før/etter (bruk ekte bilder når tilgjengelig)',
  },
  {
    week: 3,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Nytte',
    hook: 'Hvor skal det stå? Garasje, bod, kjeller, loft',
    cta: 'DM bilde av rotet',
    notes: 'Bilder ulike rom',
  },
  {
    week: 3,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Håndverk',
    hook: 'Ekte tre, opp mot taket – utnytter hele høyden',
    cta: '—',
    notes: 'V29/V30_9x16',
  },
  {
    week: 3,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Nytte/FAQ',
    hook: 'Er det søknadspliktig? Og andre spørsmål folk lurer på',
    cta: 'Lagre',
    notes: 'Basert på lead-skjema spørsmål',
  },
  {
    week: 3,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: '6 s teaser: slutt på rotet + pris',
    cta: 'Få pris',
    notes: '6 s teaser V13',
  },
  {
    week: 3,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Bak kulissene',
    hook: 'Leveringsdag / bil lastet med rack',
    cta: '—',
  },
  {
    week: 3,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Design',
    hook: '«Ro og orden»-stemningsbilde',
    cta: 'Følg',
  },

  // UKE 4 – «Skala + community + tilbud»
  {
    week: 4,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Før/etter',
    hook: 'Ny transformasjon / kundeklipp (m/ samtykke)',
    cta: 'Del',
  },
  {
    week: 4,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Nytte',
    hook: 'Send et bilde av dagens rot – vi finner riktig størrelse og pris',
    cta: 'DM «ORDEN»',
    notes: 'Basert på lead-skjema (uforpliktende)',
  },
  {
    week: 4,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: 'Billigere enn IKEA-hyller – regn på det først',
    cta: 'DM «ORDEN»',
    notes: 'V09/V31 direkte sammenligning',
  },
  {
    week: 4,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Merkevare',
    hook: 'Presenter produktfamilien: Skjul · Ved · Orden',
    cta: 'Følg',
  },
  {
    week: 4,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Tilbud',
    hook: 'Introduksjonspris – begrenset antall oppdrag nå',
    cta: 'Få pris',
    notes: 'V33/V35 – kun hvis ekte',
  },
  {
    week: 4,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Bak kulissene',
    hook: 'Del en følger-DM/spørsmål (m/ samtykke)',
    cta: 'Spør oss',
  },
  {
    week: 4,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Oppsummering måned 1 + takk',
    cta: 'Følg',
  },
];
