import type { TemplateSeed } from './calendar-skjul';

export const ROVERK_CALENDAR_ID = 'roverk-v1';

export const roverkTemplates: TemplateSeed[] = [
  // UKE 1 – «Dette er Roverk»
  {
    week: 1,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Merkevare',
    hook: '«Nytt lokalt: Roverk – bygget for orden.» Kort intro til hvem vi er',
    cta: 'Følg',
    notes: 'Tagg alle 3 produktkontoer',
  },
  {
    week: 1,
    day: 'Ons',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Produktfamilie',
    hook: '«Tre måter Roverk skaper orden: Skjul · Ved · Orden»',
    cta: 'Se produktene',
    notes: 'Lenk hver til sin konto',
  },
  {
    week: 1,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Håndverk',
    hook: '«Slik lages et Roverk» – verkstedklipp',
    cta: 'Lagre',
    notes: 'Krever filming — verksted. Repost til produktkontoene',
  },
  {
    week: 1,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Sitat-kort «Bygget for orden.» + monogram',
    cta: '—',
  },

  // UKE 2 – «Menneskene og håndverket»
  {
    week: 2,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Grunnlegger',
    hook: '«Hvorfor vi startet Roverk» – grunnleggerens historie',
    cta: '—',
    notes: 'Krever filming — grunnlegger',
  },
  {
    week: 2,
    day: 'Ons',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Håndverk',
    hook: 'Nærbilde materialer/detaljer: «Ekte tre, ikke flatpakke»',
    cta: 'Lagre',
    notes: 'Felles for alle produkter',
  },
  {
    week: 2,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Transformasjon',
    hook: '«Fra rot til orden» – beste før/etter fra et produkt',
    cta: 'Del',
    notes: 'Collab m/ det produktet',
  },
  {
    week: 2,
    day: 'Søn',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Bak kulissene',
    hook: 'Helg på verkstedet, poll',
    cta: '—',
    notes: 'Del produktinnlegg',
  },

  // UKE 3 – «Løsningene i bruk»
  {
    week: 3,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produktfamilie',
    hook: '«Hvilken Roverk-løsning passer deg?» rask guide',
    cta: 'Se produktene',
    notes: 'Lenk alle 3 produkter',
  },
  {
    week: 3,
    day: 'Ons',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Felles verdi',
    hook: '«Alt vi leverer er ferdig montert – du løfter ikke en finger»',
    cta: 'Lagre',
    notes: 'Gjelder alle produkter',
  },
  {
    week: 3,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Transformasjon',
    hook: 'Ny før/etter (annet produkt)',
    cta: 'Del',
    notes: 'Collab m/ det produktet',
  },
  {
    week: 3,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Lokalt',
    hook: '«Håndbygd i Trondheim» stemningsbilde',
    cta: '—',
  },

  // UKE 4 – «Merkevaren som varer»
  {
    week: 4,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Merkevare',
    hook: '«Det der ser ut som et Roverk» – hva vi bygger mot',
    cta: 'Følg',
    notes: 'Tagg produktkontoene',
  },
  {
    week: 4,
    day: 'Ons',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Håndverk',
    hook: 'Detalj/presisjon-klipp',
    cta: 'Lagre',
    notes: 'Repost fra produktkonto',
  },
  {
    week: 4,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produktfamilie',
    hook: 'Måned oppsummert: se alt Roverk har laget',
    cta: 'Se produktene',
    notes: 'Lenk alle 3 produkter',
  },
  {
    week: 4,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Takk + veien videre',
    cta: 'Følg',
  },
];
