import type { TemplateSeed } from './calendar-skjul';

export const VED_CALENDAR_ID = 'ved-v1';

export const vedTemplates: TemplateSeed[] = [
  // UKE 1 (14.–20. juli) – «Hvem er vi + problemet»
  {
    week: 1,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Merkevare',
    hook: '«Nytt lokalt: Roverk Ved – tørr ved hele vinteren»',
    cta: 'Følg',
    notes: 'V01_9x16',
  },
  {
    week: 1,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Nytte',
    hook: 'Vått ved-lager? Det stjeler varme og gir røyk.',
    cta: 'Lagre',
    notes: 'Scene 5 (vinter)',
  },
  {
    week: 1,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: '11 s: tørr ved + uten søknad',
    cta: 'DM «VED»',
    notes: 'V05_9x16',
  },
  {
    week: 1,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'FAQ',
    hook: '«Er vedskjul søknadspliktig?» → nei (frittstående)',
    cta: 'Del',
    notes: 'Scene 1 + tekst',
  },
  {
    week: 1,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Håndverk',
    hook: '«Slik starter et Roverk Ved» – verksted/precut',
    cta: 'DM «VED»',
    notes: 'V25_9x16',
  },
  {
    week: 1,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Bak kulissene',
    hook: 'Verksted, kaffe, «helg på verkstedet»',
    cta: 'Poll',
    notes: 'klipp video6',
  },
  {
    week: 1,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Sitat-kort «Bygget for orden.» + logo',
    cta: '—',
    notes: 'Scene 10',
  },

  // UKE 2 (21.–27. juli) – «Slik funker det + tillit»
  {
    week: 2,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Prosess',
    hook: '«Fra bestilling til ferdig montert – 3 faser»',
    cta: 'DM «VED»',
    notes: 'V03_9x16',
  },
  {
    week: 2,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Detalj',
    hook: '«Bratt tak + luftespalter = veden holder seg tørr»',
    cta: 'Lagre',
    notes: 'Scene 6',
  },
  {
    week: 2,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Trygghet',
    hook: '«Betal først når det står ferdig»',
    cta: 'Få pris',
    notes: 'V11_9x16',
  },
  {
    week: 2,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Produkt',
    hook: 'Tre størrelser: 1 000 / 2 500 / 5 000 liter',
    cta: 'Kommenter',
    notes: 'Scene 4',
  },
  {
    week: 2,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Nytte',
    hook: '«Slutt med presenning og kaos»',
    cta: 'DM «VED»',
    notes: 'V09_9x16',
  },
  {
    week: 2,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'FAQ',
    hook: '«Spør oss om alt» – svar i DM',
    cta: 'Spørsmål-sticker',
  },
  {
    week: 2,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Hvorfor Roverk? Grunnleggerens historie',
    cta: 'Følg',
    notes: 'Scene 2',
  },

  // UKE 3 (28. juli–3. aug) – «Håndverk + prosess»
  {
    week: 3,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Håndverk',
    hook: 'Nærbilde: overlappende kledning + åpne gavler',
    cta: 'Lagre',
    notes: 'V25_9x16',
  },
  {
    week: 3,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Detalj',
    hook: '«Hevet bunnramme holder veden borte fra fukt»',
    cta: '—',
    notes: 'Scene 6',
  },
  {
    week: 3,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Prosess',
    hook: '«Precut på verkstedet = rask montering hjemme»',
    cta: 'DM «VED»',
    notes: 'video6-klipp',
  },
  {
    week: 3,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Nytte',
    hook: '«Slik loader du ved fra begge ender»',
    cta: 'Lagre',
    notes: 'Scene 1 + tekst',
  },
  {
    week: 3,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Design',
    hook: '«Et vedskjul du vil ha stående ute»',
    cta: 'Få pris',
    notes: 'V27_9x16',
  },
  {
    week: 3,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Bak kulissene',
    hook: 'Leveringsdag / bil lastet med moduler',
    cta: 'Nedtelling',
  },
  {
    week: 3,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: '«Ro og orden»-stemningsbilde',
    cta: 'Følg',
    notes: 'Scene 10',
  },

  // UKE 4 (4.–10. aug) – «Størrelser + velg riktig»
  {
    week: 4,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: 'Sortiment: Liten/Medium/Stor side om side',
    cta: 'DM «VED»',
    notes: 'V17_9x16',
  },
  {
    week: 4,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Nytte',
    hook: '«Liten – ~1 000 liter. Passer den deg?»',
    cta: 'Kommenter',
    notes: 'V19 (still/klipp)',
  },
  {
    week: 4,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: '«Medium – ~2 500 liter» spotlight',
    cta: 'Få pris',
    notes: 'V21_9x16',
  },
  {
    week: 4,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'FAQ',
    hook: '«5 ting folk lurer på» (pris, søknad, tid, volum, betaling)',
    cta: 'Lagre',
    notes: 'Scene 3',
  },
  {
    week: 4,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: '«Stor – ~5 000 liter» spotlight',
    cta: 'DM «VED»',
    notes: 'V23_9x16',
  },
  {
    week: 4,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Interaktiv',
    hook: 'Poll: «Hvor mye ved fyrer du i året?»',
    cta: 'Poll',
  },
  {
    week: 4,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Produktfamilien: Skjul · Ved · Orden',
    cta: 'Følg',
    notes: 'logo + scener',
  },

  // UKE 5 (11.–17. aug) – «Design + uterom»
  {
    week: 5,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Design',
    hook: 'Hero i gyllen kveldslys',
    cta: 'Lagre',
    notes: 'V15_9x16',
  },
  {
    week: 5,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Estetikk',
    hook: 'Ved ved terrassen/uteplassen',
    cta: '—',
    notes: 'Scene 8',
  },
  {
    week: 5,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Livsstil',
    hook: 'Person henter ved – varm hverdagsstemning',
    cta: 'DM «VED»',
    notes: 'V29_9x16',
  },
  {
    week: 5,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Nytte',
    hook: '«Passer din bolig?» – ulike bakgrunner',
    cta: 'DM bilde',
    notes: 'Scene 1,2,7,8',
  },
  {
    week: 5,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: '6 s teaser: design + pris',
    cta: 'Få pris',
    notes: 'V15_9x16',
  },
  {
    week: 5,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Bak kulissene',
    hook: '«Denne uka bygger vi …»',
    cta: '—',
    notes: 'klipp',
  },
  {
    week: 5,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Stemningsbilde kyst/sommer',
    cta: 'Følg',
    notes: 'Scene 7',
  },

  // UKE 6 (18.–24. aug) – «Sesongstart: klargjør før vinteren»
  {
    week: 6,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Sesong',
    hook: '«Vinteren kommer – er veden klar?»',
    cta: 'DM «VED»',
    notes: 'V33_9x16',
  },
  {
    week: 6,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Nytte',
    hook: '«Ved trenger å tørke i god tid – begynn nå»',
    cta: 'Lagre',
    notes: 'Scene 3',
  },
  {
    week: 6,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Trygghet',
    hook: '«Levert & montert før fyringssesongen»',
    cta: 'Få pris',
    notes: 'V11_9x16',
  },
  {
    week: 6,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Prosess',
    hook: '«Bestill nå = ferdig før høsten» tidslinje',
    cta: 'DM «VED»',
    notes: 'Scene 4',
  },
  {
    week: 6,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: 'Full historie (høst-vinkel)',
    cta: 'Få pris',
    notes: 'V03_9x16',
  },
  {
    week: 6,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Interaktiv',
    hook: 'Nedtelling «X uker til fyringssesong»',
    cta: 'Sticker',
  },
  {
    week: 6,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: '«Bygget for orden» + logo',
    cta: 'Følg',
    notes: 'Scene 10',
  },

  // UKE 7 (25.–31. aug) – «Bevis + variasjon»
  {
    week: 7,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Bevis',
    hook: 'Første ekte kunde/montering (m/ samtykke) – ellers hero',
    cta: 'Del',
    notes: 'ekte klipp / V01',
  },
  {
    week: 7,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Nytte',
    hook: '«Slik måler du opp for riktig størrelse»',
    cta: 'Lagre',
    notes: 'Scene 4',
  },
  {
    week: 7,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Håndverk',
    hook: 'Detalj: hvordan taket feller snø (63° vinkel)',
    cta: '—',
    notes: 'V25_9x16',
  },
  {
    week: 7,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'FAQ',
    hook: '«Hvor leverer vi?» (Trondheim/Melhus/Malvik)',
    cta: 'DM «VED»',
    notes: 'Scene 1',
  },
  {
    week: 7,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: 'Vinter-teaser + pris',
    cta: 'Få pris',
    notes: 'V13_9x16',
  },
  {
    week: 7,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Community',
    hook: 'Del en følger-DM/spørsmål (m/ samtykke)',
    cta: 'Spør oss',
  },
  {
    week: 7,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Stemningsbilde hytte/vinter',
    cta: 'Følg',
    notes: 'Scene 3',
  },

  // UKE 8 (1.–7. sept) – «Tilbud + community»
  {
    week: 8,
    day: 'Man',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Tilbud',
    hook: 'Introduksjonspris / ledige monteringsdatoer (kun hvis ekte)',
    cta: 'Få pris',
    notes: 'V35_9x16',
  },
  {
    week: 8,
    day: 'Tir',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Nytte',
    hook: '«Fortsatt ledig for montering før høsten»',
    cta: 'DM «VED»',
    notes: 'Scene 5',
  },
  {
    week: 8,
    day: 'Ons',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Sesong',
    hook: '«Sikre din plass før fyringssesongen»',
    cta: 'Få pris',
    notes: 'V33_9x16',
  },
  {
    week: 8,
    day: 'Tor',
    platform: 'instagram',
    format: 'karusell',
    pillar: 'Bevis/FAQ',
    hook: 'Oppsummering: hvorfor Roverk Ved (5 punkter)',
    cta: 'Lagre',
    notes: 'Scene 4,6,10',
  },
  {
    week: 8,
    day: 'Fre',
    platform: 'instagram',
    format: 'Reels',
    pillar: 'Produkt',
    hook: 'Full historie 17 s (beste versjon)',
    cta: 'Få pris',
    notes: 'V01_9x16',
  },
  {
    week: 8,
    day: 'Lør',
    platform: 'instagram',
    format: 'Stories',
    pillar: 'Community',
    hook: 'Takk + «tagg noen som trenger tørr ved»',
    cta: 'Del',
  },
  {
    week: 8,
    day: 'Søn',
    platform: 'instagram',
    format: 'feed',
    pillar: 'Merkevare',
    hook: 'Oppsummering + veien videre',
    cta: 'Følg',
    notes: 'Scene 10',
  },
];
